package com.siebel.customui;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-04T18:24:44+03:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "UAL_spcPromotion_spcCodes_spcService",
                  wsdlLocation = "file:src/main/resources/siebel.wsdl",
                  targetNamespace = "http://siebel.com/CustomUI")
public class UALSpcPromotionSpcCodesSpcService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://siebel.com/CustomUI", "UAL_spcPromotion_spcCodes_spcService");
    public final static QName UALSpcPromotionSpcCodesSpcService = new QName("http://siebel.com/CustomUI", "UAL_spcPromotion_spcCodes_spcService");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/siebel.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UALSpcPromotionSpcCodesSpcService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/siebel.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UALSpcPromotionSpcCodesSpcService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UALSpcPromotionSpcCodesSpcService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UALSpcPromotionSpcCodesSpcService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UALSpcPromotionSpcCodesSpcService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UALSpcPromotionSpcCodesSpcService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UALSpcPromotionSpcCodesSpcService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns UALSpcPromotionSpcCodesSpcService
     */
    @WebEndpoint(name = "UAL_spcPromotion_spcCodes_spcService")
    public UALSpcPromotionSpcCodesSpcService getUALSpcPromotionSpcCodesSpcService() {
        return super.getPort(UALSpcPromotionSpcCodesSpcService, UALSpcPromotionSpcCodesSpcService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UALSpcPromotionSpcCodesSpcService
     */
    @WebEndpoint(name = "UAL_spcPromotion_spcCodes_spcService")
    public UALSpcPromotionSpcCodesSpcService getUALSpcPromotionSpcCodesSpcService(WebServiceFeature... features) {
        return super.getPort(UALSpcPromotionSpcCodesSpcService, UALSpcPromotionSpcCodesSpcService.class, features);
    }

}
